export default function ExportActions({ meta, details, event, timeline, experts, matrix, gaps, documents }) {
  const table = (headers, rows) => `<table><thead><tr>${headers.map((header) => `<th>${header}</th>`).join("")}</tr></thead><tbody>${rows.map((row) => `<tr>${row.map((cell) => `<td>${cell || ""}</td>`).join("")}</tr>`).join("")}</tbody></table>`;
  const html = () => `<!doctype html><html lang="he" dir="rtl"><head><meta charset="utf-8"><title>פרופיל תביעה</title><style>body{font-family:Arial;max-width:1000px;margin:32px auto;line-height:1.6;color:#171746}h1,h2{color:#020140}h3{margin-bottom:4px}table{width:100%;border-collapse:collapse;margin:8px 0 18px}th,td{border:1px solid #ddd;padding:7px;text-align:right;vertical-align:top}th{background:#f1f4f8}.muted{color:#666;font-size:12px}</style></head><body><h1>פרופיל תביעה - ${meta.insuredName}</h1><p><b>תעודת זהות:</b> ${meta.insuredId} | <b>מספר תביעה:</b> ${meta.claimNumber} | <b>פוליסה:</b> ${meta.policyNumber} | <b>תאריך דוח:</b> ${meta.reportDate} | <b>מהות:</b> ${meta.type}</p><h2>פרטים כלליים</h2><ul>${details.map(([label, value]) => `<li><b>${label}:</b> ${value}</li>`).join("")}</ul><h2>נסיבות האירוע</h2><p>${event.text}</p><p class="muted"><b>מקורות:</b> ${event.sources.map((source) => `${source.title} (${source.date})`).join("; ")}</p><h2>סיכום רפואי כרונולוגי</h2>${timeline.map((item) => `<h3>${item.date} - ${item.title}</h3><p>${item.full || item.summary}</p><p class="muted">מקור: ${item.source?.title || ""} ${item.source?.date ? `(${item.source.date})` : ""}</p>`).join("")}<h2>חוות דעת מומחים</h2>${experts.map((item) => `<h3>${item.date} - ${item.name} - ${item.role}</h3><p>${item.full || item.opinion}</p><p><b>נכות:</b> ${item.disability || ""}</p>${item.breakdown?.length ? `<ul>${item.breakdown.map((part) => `<li>${part.label}: ${part.value}</li>`).join("")}</ul>` : ""}<p class="muted">מקור: ${item.source?.title || ""}</p>`).join("")}<h2>טבלת הערכות נכות</h2>${table(["תחום", "ד\"ר מיכאל צור", "ד\"ר יריב גולדשטיין", "פרופ' אבינועם רכס", "ד\"ר אדם דרנל", "פרופ' אורי אלקיים", "מל\"ל", "הערת פער"], matrix)}<h2>סתירות ופערים</h2>${gaps.map((gap) => `<h3>${gap.topic}</h3><p>${gap.detail}</p><p><b>גורם א׳:</b> ${gap.positionA}<br>${gap.whatA}</p><p><b>גורם ב׳:</b> ${gap.positionB}<br>${gap.whatB}</p>`).join("")}<h2>מסמכים שנקראו</h2>${table(["שם מסמך", "סוג מסמך / כותרת", "תאריך מסמך", "נכלל בסיכום", "מקור", "חילוץ %", "הערות AI על החילוץ"], documents.map((doc) => [doc.name, doc.type, doc.date, doc.included, doc.source?.title || "", doc.extraction, doc.aiNotes]))}<h2>מנגנון המלצה עתידי</h2><p>רכיב המלצות עתידי מוצג במערכת כיכולת עתידית ואינו חלק מהניתוח הנוכחי.</p><small>סיכום זה הופק באמצעות מערכת בינה מלאכותית (AI) ועלול להכיל טעויות. יש לבצע בדיקה ואימות מול המסמכים המקוריים לפני קבלת החלטה.</small></body></html>`;
  const exportHtml = () => {
    const file = new Blob([html()], { type: "text/html;charset=utf-8" });
    const url = URL.createObjectURL(file);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = `claim-profile-${meta.claimNumber}.html`;
    anchor.click();
    URL.revokeObjectURL(url);
  };
  return <div className="export-actions"><button className="ghost-button" onClick={exportHtml}>ייצוא HTML</button><button className="primary-button" onClick={() => window.print()}>ייצוא PDF</button></div>;
}
